version: "3.7"

services:
  app:
    container_name: my_server
    build: .
    command: sh -c "npm install && npm run dev"
    ports:
      - 8080:8080
    working_dir: /app
    environment:
      DATABASE_URL: postgres://user:12345@postgres:5432/list
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: my_database
    image: postgres:11
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: list
    ports: 
      - '35432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
